import type { User, Category, Product } from './types';

export const users: User[] = [
  { id: 'user-1', name: 'Alex Johnson', avatarUrl: 'https://picsum.photos/seed/u1/100/100', isVerified: true },
  { id: 'user-2', name: 'Maria Garcia', avatarUrl: 'https://picsum.photos/seed/u2/100/100', isVerified: true },
  { id: 'user-3', name: 'Chen Wei', avatarUrl: 'https://picsum.photos/seed/u3/100/100', isVerified: false },
  { id: 'user-admin', name: 'Dr. Admin', avatarUrl: 'https://picsum.photos/seed/ua1/100/100', isVerified: true },
];

export const categories: Category[] = [
  { id: 'cat-1', name: 'Textbooks' },
  { id: 'cat-2', name: 'Electronics' },
  { id: 'cat-3', name: 'Apparel' },
  { id: 'cat-4', name: 'Transportation' },
  { id: 'cat-5', name: 'Stationery' },
  { id: 'cat-6', name: 'Furniture' },
  { id: 'cat-7', name: 'Services' },
  { id: 'cat-8', name: 'Others' },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Introduction to Quantum Physics Textbook',
    description: 'Slightly used textbook for PHYS201. No highlights or markings. Latest edition.',
    price: 150.00,
    category: categories[0],
    seller: users[0],
    imageUrls: ['https://picsum.photos/seed/101/600/400', 'https://picsum.photos/seed/111/600/400'],
    dateAdded: '2024-07-20T10:00:00Z',
    condition: 'Used - Like New',
  },
  {
    id: 'prod-2',
    name: 'MacBook Air M1 2020',
    description: 'Well-maintained MacBook Air, perfect for students. 8GB RAM, 256GB SSD. Comes with charger.',
    price: 2800.00,
    category: categories[1],
    seller: users[1],
    imageUrls: ['https://picsum.photos/seed/102/600/400', 'https://picsum.photos/seed/112/600/400'],
    dateAdded: '2024-07-19T14:30:00Z',
    condition: 'Used - Good',
  },
  {
    id: 'prod-3',
    name: 'Official USM Hoodie (Size M)',
    description: 'Authentic university hoodie. Worn only a few times. Very comfortable.',
    price: 80.00,
    category: categories[2],
    seller: users[0],
    imageUrls: ['https://picsum.photos/seed/103/600/400'],
    dateAdded: '2024-07-21T09:00:00Z',
    condition: 'Used - Like New',
  },
  {
    id: 'prod-4',
    name: 'Mountain Bike',
    description: 'A reliable mountain bike for getting around campus. Recently serviced. Some minor scratches.',
    price: 450.00,
    category: categories[3],
    seller: users[2],
    imageUrls: ['https://picsum.photos/seed/104/600/400', 'https://picsum.photos/seed/114/600/400'],
    dateAdded: '2024-07-18T11:00:00Z',
    condition: 'Used - Good',
  },
  {
    id: 'prod-5',
    name: 'Noise-Cancelling Headphones',
    description: 'Brand new, unopened noise-cancelling headphones. Great for studying in noisy environments.',
    price: 350.00,
    category: categories[1],
    seller: users[1],
    imageUrls: ['https://picsum.photos/seed/105/600/400'],
    dateAdded: '2024-07-22T16:00:00Z',
    condition: 'New',
  },
  {
    id: 'prod-6',
    name: 'Complete Organic Chemistry Notes',
    description: 'Full semester notes for KTT222. Detailed diagrams and easy-to-understand explanations. Digital PDF.',
    price: 50.00,
    category: categories[4],
    seller: users[0],
    imageUrls: ['https://picsum.photos/seed/106/600/400'],
    dateAdded: '2024-07-15T08:00:00Z',
    condition: 'New',
  },
  {
    id: 'prod-7',
    name: 'Scientific Calculator',
    description: 'Casio fx-570EX scientific calculator. Approved for use in examinations.',
    price: 75.00,
    category: categories[4],
    seller: users[2],
    imageUrls: ['https://picsum.photos/seed/107/600/400'],
    dateAdded: '2024-07-20T18:00:00Z',
    condition: 'Used - Like New',
  },
  {
    id: 'prod-8',
    name: 'Ergonomic Desk Chair',
    description: 'Comfortable ergonomic chair, perfect for long study sessions. Adjustable height and back support.',
    price: 250.00,
    category: categories[5],
    seller: users[1],
    imageUrls: ['https://picsum.photos/seed/118/600/400'],
    dateAdded: '2024-07-21T12:00:00Z',
    condition: 'Used - Good',
  },
];
